"""books

Revision ID: 4d4033d84d0e
Revises: 
Create Date: 2025-10-27 20:07:02.248341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4033d84d0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.String(length=50), nullable=True),
    sa.Column('publishing_house', sa.String(length=100), nullable=True),
    sa.Column('series', sa.String(length=50), nullable=True),
    sa.Column('isbn', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('number_of_pages', sa.String(length=20), nullable=True),
    sa.Column('image_link', sa.String(length=255), nullable=True),
    sa.Column('image_name', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('book_format', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('initial_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('isbn', name=op.f('pk_books'))
    )
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_index(op.f('ix_books_sku'), 'books', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_sku'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
